### ISSUE TITLE
Dataset for train

### ISSUE THREAD

**Issue by zhhaochen** [williamljb/HumanMultiView#6]
Hi, thanks for your nice work.  
If I want to train, should I use all datasets or only the synthetic tfrecords I download ?
And should I crop the mpi_inf_3dhp dataset?

**Comment by williamljb** [comment]
All datasets, as described in dataloader.py.
Note that the numbers in dataloader.py are only indicators of epoch sizes, not the actual dataset split. The split is written in get_loader_w3d.

**Comment by zhhaochen** [comment]
> All datasets, as described in dataloader.py.
> Note that the numbers in dataloader.py are only indicators of epoch sizes, not the actual dataset split. The split is written in get_loader_w3d.

The mocap_datasets is not defined in config.py whild hmr use it. Should I use it?

**Comment by williamljb** [comment]
No. mocap_datasets are used in hmr for the discriminator. Our network doesn't need this.

**Comment by zhhaochen** [comment]
> No. mocap_datasets are used in hmr for the discriminator. Our network doesn't need this.

Thanks for your reply!
